# Generated by Django 5.2.6 on 2025-09-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_sizes_size_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.ManyToManyField(related_name='categories', to='products.gender'),
        ),
    ]
