# Generated by Django 5.2.6 on 2025-09-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gender',
        ),
    ]
