# Generated by Django 5.2.6 on 2025-09-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gender',
        ),
    ]
