# Generated by Django 5.2.6 on 2025-09-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_image_url_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='varian',
            new_name='variant',
        ),
    ]
