# Generated by Django 5.2.6 on 2025-09-28 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_varian_image_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.color'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.size'),
        ),
    ]
