# Generated by Django 5.2.6 on 2025-11-01 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_variant_color_alter_variant_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='variant',
            name='price',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('product', 'color'), name='unique_product_color'),
        ),
        migrations.AddField(
            model_name='variantsizes',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_sizes', to='products.size'),
        ),
        migrations.AddField(
            model_name='variantsizes',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_sizes', to='products.variant'),
        ),
    ]
