# Generated by Django 5.2.6 on 2025-11-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_variantsizes_remove_variant_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariantSizes',
            new_name='VariantSize',
        ),
    ]
