# Generated by Django 5.2.6 on 2025-11-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_variantsizes_variantsize'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='variantsize',
            constraint=models.UniqueConstraint(fields=('variant', 'size'), name='unique_variant_size'),
        ),
    ]
