# Generated by Django 5.2.6 on 2025-11-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_variantsize_unique_variant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
